# App name
spring.application.name=agriconnect-backend

# ==============================
# MySQL Database - Railway
# ==============================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# ==============================
# JPA / Hibernate
# ==============================
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ==============================
# Server Port
# ==============================
server.port=${PORT:8080}

# ==============================
# JWT
# ==============================
jwt.secret=${JWT_SECRET:your256bitsecretkeyforjwtsigningmustbeatleast32byteslong123456}
jwt.expiration=86400000

# ==============================
# File Upload Limits
# ==============================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ==============================
# AGMARKNET Government Market Price API
# ==============================
agmarknet.api.key=YOUR_AGMARKNET_API_KEY
agmarknet.api.url=https://api.data.gov.in/resource/9ef84268-d588-465a-a308-a864a43d0070

# ==============================
# Google Authentication
# ==============================
google.client.id=655567649384-c5rdossoot8plcrvku6fftkm0c9hf036.apps.googleusercontent.com